### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [JayBuckby/portfolio-challenge#1]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages) : DONE
2. A public GitHub repository for your codebase : DONE
3. Use HTML & SCSS : DONE
4. Make good use of semantic HTML elements : DONE
5. Be responsive (mobile-first) and built with accessibility in mind : DONE
6. Code is highly readable (good naming and indented correctly) : DONE - Needs work

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Augusta-Course-Resources/blob/main/student-resources/00-slides/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 30 / 50  |
| Responsiveness       | 10 / 15  |
| Code Knowledge & Use | 15 / 20  |
| Readability          | 10 / 15  |
| Version Control      | 10 / 10  |
| Total Score          | 75 / 110 |

## Positive

As your first project I think that this is a success, you have clearly enjoyed coding a website from a wire frame. If you ever need a break pick a website and try and recreate it.

The website looks great on mobile, and almost matches the design. There are a couple of tweaks you will need to make mainly around spacing on desktop. Everything feels pretty squished so make use of padding and margin to add space between your html elements. You also have a slight side wiggle scroll on desktop.

```scss
// _components.scss

nav {
  // width: 100vw; REMOVE THIS LINE
  height: 15vh;
  display: none;
}
```

You have started to customize the project which is great!

- This is a good place to play around with adding functionality with JS!

Great use of Git and Github, keep on committing with meaningful messages. 

You are demonstrating a solid understanding of the majority of topics we have covered so far, keep it up and keep on using BEM, SCSS, grid and flex :D.

## Constructive

- You are using a `<logo>` tag in your html. This tag isn't an actual HTML tag. Book mark [W3 Element Ref](https://www.w3schools.com/TAGS/default.asp) and make sure you use those tags.

- You may have relied on the grid generator a little bit to much, don't get me wrong it is a great tool but for a simple grid it has over complicated some of your styles, which can be removed see below.

- Your BEM is a bit hit and miss which is fine as it takes practice.

  - names are lowercase hyphenated if multiple words. Camel casing is for JS.
  - You want avoid using any html css selectors, the rule is everything that is going to have specific styles needs a class name. Resets are the exception.

Lets compare HTML.

```html
<section class="technicalSkills">
  <h2>Technical Skills</h2>
  <p>
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis natus vitae fuga quibusdam cupiditate sint
    delectus aut quaerat id, voluptatibus accusantium alias perspiciatis! Placeat, unde vitae molestias neque modi esse.
  </p>
  <div class="technicalSkills__container">
    <div>
      <img class="technicalSkills__container--img1" src="./images/springboot.png" />
      <p>Springboot</p>
    </div>
    <div>
      <img class="technicalSkills__container--img2" src="./images/java.png" />
      <p>Java</p>
    </div>
    <div>
      <img class="technicalSkills__container--img3" src="./images/react.png" />
      <p>React</p>
    </div>
    <div>
      <img class="technicalSkills__container--img4" src="./images/bem.png" />
      <p>BEM</p>
    </div>
    <div>
      <img class="technicalSkills__container--img5" src="./images/sass.png" />
      <p>SCSS</p>
    </div>
    <div>
      <img class="technicalSkills__container--img6" src="./images/js.png" />
      <p>JavaScript</p>
    </div>
    <div>
      <img class="technicalSkills__container--img7" src="./images/css.png" />
      <p>CSS3</p>
    </div>
    <div>
      <img class="technicalSkills__container--img8" src="./images/html5.png" />
      <p>HTML5</p>
    </div>
    <div>
      <img class="technicalSkills__container--img9" src="./images/git.png" />
      <p>GIT</p>
    </div>
  </div>
</section>

<!-- WOULD BE -->
<!-- LOWERCASE HYPHENATED FOR MULTIPLE WORDS -->
<section class="technical-skills">
  <h2 class="technical-skills__title">Technical Skills</h2>
  <p>
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis natus vitae fuga quibusdam cupiditate sint
    delectus aut quaerat id, voluptatibus accusantium alias perspiciatis! Placeat, unde vitae molestias neque modi esse.
  </p>
  <div class="technical-skills__list">
    <div>
      <!-- EXAMPLE IF YOU DID NEED A MODIFIER -->
      <img class="technical-skills__image technical-skills__image--1" src="./images/springboot.png" />
      <p>Springboot</p>
    </div>
    <div>
      <img src="./images/java.png" />
      <p>Java</p>
    </div>
    <div>
      <img src="./images/react.png" />
      <p>React</p>
    </div>
    <div>
      <img src="./images/bem.png" />
      <p>BEM</p>
    </div>
    <div>
      <img src="./images/sass.png" />
      <p>SCSS</p>
    </div>
    <div>
      <img src="./images/js.png" />
      <p>JavaScript</p>
    </div>
    <div>
      <img src="./images/css.png" />
      <p>CSS3</p>
    </div>
    <div>
      <img src="./images/html5.png" />
      <p>HTML5</p>
    </div>
    <div>
      <img src="./images/git.png" />
      <p>GIT</p>
    </div>
  </div>
</section>
```

Let's compare SCSS.

```scss
.technicalSkills {
  font-family: $text-primary;
  font-weight: bold;
  text-align: center;
  font-size: 1.2rem;
  h2 {
    font-family: $text-heading;
    margin: 25px;
    font-size: 2rem;
  }

  &__container {
    padding: 10%;
    display: grid;
    align-items: center;
    text-align: center;
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: repeat(3, 1fr);
    grid-column-gap: 20px;
    grid-row-gap: 20px;
    &--img1 {
      grid-area: 1 / 1 / 2 / 2;
    }
    &--img2 {
      grid-area: 1 / 2 / 2 / 3;
    }
    &--img3 {
      grid-area: 1 / 3 / 2 / 4;
    }
    &--img4 {
      grid-area: 2 / 1 / 3 / 2;
    }
    &--img5 {
      grid-area: 2 / 2 / 3 / 3;
    }
    &--img6 {
      grid-area: 2 / 3 / 3 / 4;
    }
    &--img7 {
      grid-area: 3 / 1 / 4 / 2;
    }
    &--img8 {
      grid-area: 3 / 2 / 4 / 3;
    }
    &--img9 {
      grid-area: 3 / 3 / 4 / 4;
    }
  }
}

// WOULD BE

.technical-skills {
  font-family: $text-primary;
  font-weight: bold;
  text-align: center;
  font-size: 1.2rem;

  // USING A CLASS SELECTOR
  &__title {
    font-family: $text-heading;
    margin: 25px;
    font-size: 2rem;
  }

  &__list {
    padding: 10%;
    display: grid;
    align-items: center;
    text-align: center;
    // YOU CAN SET YOUR GRID HERE & LET IT DO ALL OF THE LAYING OUT.
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: repeat(3, 1fr);
    grid-column-gap: 20px;
    grid-row-gap: 20px;
  }

  // THE GRID AREAS ON THE IMG'S CAN BE REMOVED AS THEY AREN'T DOING ANYTHING.
  
  &__img {
    
    &--1 {
    // IF YOU WANTED TO SELECT AND STYLE A MODIFIER
    }
  }
}
```

I want you to take these points further with your next project, use SCSS and the awesome features it gives you. Try using BEM for naming as well.

Reach out if you do run into any problems.

---
